### ISSUE TITLE
bug :(

### ISSUE THREAD

**Issue by withs** [TheDude7/Road2Prime#1]
Hey, the app said 

Got CSGO Window
Menu not visible, waiting 5 seconds...

my csgo is windowed 640x480

thx for your help hop you wil continue this awsome project

**Comment by withs** [comment]
after investigate i think i a color problem while searching for menu
if i try in google on a white page it work but in cs with 255 255 255 it dosn't working

**Comment by withs** [comment]
and its like for the app the game is a black window

**Comment by withs** [comment]
but i found a real issie woch is when a match is found and a guys dont accept it the program think the match is started and it show a message on the screen wich is make the bot stuck

**Comment by TheDude7** [comment]
It doesnt get stuck, it clicks the accept and then waits 3 minutes, after which it starts waiting for menu. AKA: if someone doesnt accept and it fails, it'll retry 3 minutes after. This is also to avoid "Matchmaking Service Unavailable" message

**Comment by TheDude7** [comment]
I will update soon with a version based on image matching instead of window ratios

**Comment by withs** [comment]
hi, it wasn't working on my main pc,

i put it on my laptop and it work i made some mods to get all fine ;)
but i reached lvl 10 but i win only 5 xp so its no that great ...
but your program is nice.
